apiVersion: apps/v1
kind: Deployment
metadata:
  name: 6ce17460-2163-4cff-a220-29f755929fff
  namespace: platform
  labels:
    app: platform
    uuid: 6ce17460-2163-4cff-a220-29f755929fff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform
      uuid: 6ce17460-2163-4cff-a220-29f755929fff
  template:
    metadata:
      labels:
        app: platform
        uuid: 6ce17460-2163-4cff-a220-29f755929fff
    spec:
      containers:
      - name: platform
        image: fariaass/station-core 
        env:
          - name: DOCKS_QTT
            value: "2"
          - name: HELIPADS_QTT
            value: "3"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
