apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-33aae08f-b9c4-428b-903a-38bb9fd61539
  namespace: platform
  labels:
    app: platform
    uuid: 33aae08f-b9c4-428b-903a-38bb9fd61539
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform
      uuid: 33aae08f-b9c4-428b-903a-38bb9fd61539
  template:
    metadata:
      labels:
        app: platform
        uuid: 33aae08f-b9c4-428b-903a-38bb9fd61539
    spec:
      containers:
      - name: platform
        image: fariaass/station-core 
        env:
          - name: DOCKS_QTT
            value: "1"
          - name: HELIPADS_QTT
            value: "1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
