apiVersion: apps/v1
kind: Deployment
metadata:
  name: v-39526e50-0371-49d1-9f85-4e70fbf27e2f
  namespace: helicopter
  labels:
    app: helicopter
    uuid: 39526e50-0371-49d1-9f85-4e70fbf27e2f
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helicopter
      uuid: 39526e50-0371-49d1-9f85-4e70fbf27e2f
  template:
    metadata:
      labels:
        app: helicopter
        uuid: 39526e50-0371-49d1-9f85-4e70fbf27e2f
    spec:
      containers:
      - name: helicopter
        image: fariaass/mobility-core:11
        args:
          - "39526e50-0371-49d1-9f85-4e70fbf27e2f"
          - "helicopter"
          - "70.2"
          - "71"
          - "800"
          - "towers-svc.tower.svc.cluster.local"
        envFrom:
          - secretRef:
              name: rabbitmq-credentials
          - configMapRef:
              name: vehicles-common-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
