apiVersion: apps/v1
kind: Deployment
metadata:
  name: v-dece23b1-c129-479b-ac81-6dc295d4d76a
  namespace: helicopter
  labels:
    app: helicopter
    uuid: dece23b1-c129-479b-ac81-6dc295d4d76a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helicopter
      uuid: dece23b1-c129-479b-ac81-6dc295d4d76a
  template:
    metadata:
      labels:
        app: helicopter
        uuid: dece23b1-c129-479b-ac81-6dc295d4d76a
    spec:
      containers:
      - name: helicopter
        image: fariaass/mobility-core:8
        args:
          - "dece23b1-c129-479b-ac81-6dc295d4d76a"
          - "helicopter"
          - "70.1"
          - "70.1"
          - "800"
          - "towers-svc.tower.svc.cluster.local"
        envFrom:
          - secretRef:
              name: rabbitmq-credentials
          - configMapRef:
              name: vehicles-common-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
