apiVersion: apps/v1
kind: Deployment
metadata:
  name: t-f7bb70fd-b735-4a35-b1a0-175d5d96d17a
  namespace: tower
  labels:
    app: tower
    uuid: f7bb70fd-b735-4a35-b1a0-175d5d96d17a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tower
      uuid: f7bb70fd-b735-4a35-b1a0-175d5d96d17a
  template:
    metadata:
      labels:
        app: tower
        uuid: f7bb70fd-b735-4a35-b1a0-175d5d96d17a
    spec:
      containers:
      - name: tower
        image: fariaass/com-tower:35
        envFrom:
          - secretRef:
              name: credentials
          - secretRef:
              name: email-config
          - configMapRef:
              name: towers-common-config
        env:
          - name: TOWER_ID
            value: f7bb70fd-b735-4a35-b1a0-175d5d96d17a
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
