apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-25d8d76a-180c-499e-8f70-202c4dff67a8
  namespace: platform
  labels:
    app: platform
    uuid: 25d8d76a-180c-499e-8f70-202c4dff67a8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform
      uuid: 25d8d76a-180c-499e-8f70-202c4dff67a8
  template:
    metadata:
      labels:
        app: platform
        uuid: 25d8d76a-180c-499e-8f70-202c4dff67a8
    spec:
      containers:
      - name: platform
        image: fariaass/station-core 
        env:
          - name: DOCKS_QTT
            value: "1"
          - name: HELIPADS_QTT
            value: "1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
