apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-consumer
  namespace: metrics-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-consumer
  template:
    metadata:
      labels:
        app: metrics-consumer
    spec:
      containers:
      - name: metrics-consumer
        image: fariaass/metrics-consumer:5
        envFrom:
          - secretRef:
              name: rabbitmq-credentials
        env:
          - name: PROMETHEUS_PUSHGATEWAY_HOST
            value: pushgateway.monitoring.svc.cluster.local
          - name: PROMETHEUS_PUSHGATEWAY_PORT
            value: "9091"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
