apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resource-manager-frontend
  namespace: resource-manager-frontend
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - maritime-flow.souzavinicius.com
      secretName: maritime-flow-tls-secret
  rules:
    - host: maritime-flow.souzavinicius.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: resource-manager-frontend
                port:
                  number: 4000
