apiVersion: apps/v1
kind: Deployment
metadata:
  name: t-8e570e1a-5c8c-47d9-b4f8-dda494474b30
  namespace: tower
  labels:
    app: tower
    uuid: 8e570e1a-5c8c-47d9-b4f8-dda494474b30
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tower
      uuid: 8e570e1a-5c8c-47d9-b4f8-dda494474b30
  template:
    metadata:
      labels:
        app: tower
        uuid: 8e570e1a-5c8c-47d9-b4f8-dda494474b30
    spec:
      containers:
      - name: tower
        image: fariaass/com-tower:23
        envFrom:
          - secretRef:
              name: credentials
          - configMapRef:
              name: towers-common-config
        env:
          - name: TOWER_ID
            value: 8e570e1a-5c8c-47d9-b4f8-dda494474b30
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
