apiVersion: apps/v1
kind: Deployment
metadata:
  name: v-de2af5db-3468-404a-bcd5-cda3f69f0f10
  namespace: ship
  labels:
    app: ship
    uuid: de2af5db-3468-404a-bcd5-cda3f69f0f10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ship
      uuid: de2af5db-3468-404a-bcd5-cda3f69f0f10
  template:
    metadata:
      labels:
        app: ship
        uuid: de2af5db-3468-404a-bcd5-cda3f69f0f10
    spec:
      containers:
      - name: ship
        image: fariaass/mobility-core:7
        args:
          - "de2af5db-3468-404a-bcd5-cda3f69f0f10"
          - "ship"
          - "70"
          - "70"
          - "800"
          - "towers-svc.tower.svc.cluster.local"
        envFrom:
          - secretRef:
              name: rabbitmq-credentials
          - configMapRef:
              name: vehicles-common-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
