apiVersion: v1
kind: ConfigMap
metadata:
  name: vehicles-common-config
  namespace: ship
data:
  BASE_DNS: tower.svc.cluster.local
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vehicles-common-config
  namespace: helicopter
data:
  BASE_DNS: tower.svc.cluster.local
