apiVersion: apps/v1
kind: Deployment
metadata:
  name: v-15c27c45-491e-421a-80e1-e9639f49083b
  namespace: helicopter
  labels:
    app: helicopter
    uuid: 15c27c45-491e-421a-80e1-e9639f49083b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helicopter
      uuid: 15c27c45-491e-421a-80e1-e9639f49083b
  template:
    metadata:
      labels:
        app: helicopter
        uuid: 15c27c45-491e-421a-80e1-e9639f49083b
    spec:
      containers:
      - name: helicopter
        image: fariaass/mobility-core:9
        args:
          - "15c27c45-491e-421a-80e1-e9639f49083b"
          - "helicopter"
          - "70"
          - "70"
          - "800"
          - "towers-svc.tower.svc.cluster.local"
        envFrom:
          - secretRef:
              name: rabbitmq-credentials
          - configMapRef:
              name: vehicles-common-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
