apiVersion: apps/v1
kind: Deployment
metadata:
  name: v-9d8c8c5d-568d-4d0f-9735-40fbd33fec2a
  namespace: helicopter
  labels:
    app: helicopter
    uuid: 9d8c8c5d-568d-4d0f-9735-40fbd33fec2a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helicopter
      uuid: 9d8c8c5d-568d-4d0f-9735-40fbd33fec2a
  template:
    metadata:
      labels:
        app: helicopter
        uuid: 9d8c8c5d-568d-4d0f-9735-40fbd33fec2a
    spec:
      containers:
      - name: helicopter
        image: fariaass/mobility-core:11
        args:
          - "9d8c8c5d-568d-4d0f-9735-40fbd33fec2a"
          - "helicopter"
          - "71"
          - "69"
          - "800"
          - "towers-svc.tower.svc.cluster.local"
        envFrom:
          - secretRef:
              name: rabbitmq-credentials
          - configMapRef:
              name: vehicles-common-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
