apiVersion: apps/v1
kind: Deployment
metadata:
  name: t-880b3ab2-fae8-429e-a5f8-512cc27339d8
  namespace: tower
  labels:
    app: tower
    uuid: 880b3ab2-fae8-429e-a5f8-512cc27339d8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tower
      uuid: 880b3ab2-fae8-429e-a5f8-512cc27339d8
  template:
    metadata:
      labels:
        app: tower
        uuid: 880b3ab2-fae8-429e-a5f8-512cc27339d8
    spec:
      containers:
      - name: tower
        image: fariaass/com-tower:33
        envFrom:
          - secretRef:
              name: credentials
          - secretRef:
              name: email-config
          - configMapRef:
              name: towers-common-config
        env:
          - name: TOWER_ID
            value: 880b3ab2-fae8-429e-a5f8-512cc27339d8
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
