apiVersion: apps/v1
kind: Deployment
metadata:
  name: v-be600f5f-0d13-46a3-91c2-18388ae99942
  namespace: ship
  labels:
    app: ship
    uuid: be600f5f-0d13-46a3-91c2-18388ae99942
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ship
      uuid: be600f5f-0d13-46a3-91c2-18388ae99942
  template:
    metadata:
      labels:
        app: ship
        uuid: be600f5f-0d13-46a3-91c2-18388ae99942
    spec:
      containers:
      - name: ship
        image: fariaass/mobility-core:11
        args:
          - "be600f5f-0d13-46a3-91c2-18388ae99942"
          - "ship"
          - "72"
          - "71"
          - "800"
          - "towers-svc.tower.svc.cluster.local"
        envFrom:
          - secretRef:
              name: rabbitmq-credentials
          - configMapRef:
              name: vehicles-common-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
