apiVersion: apps/v1
kind: Deployment
metadata:
  name: t-49a02fde-c4c2-4cbb-9e92-81e4eaf4f095
  namespace: tower
  labels:
    app: tower
    uuid: 49a02fde-c4c2-4cbb-9e92-81e4eaf4f095
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tower
      uuid: 49a02fde-c4c2-4cbb-9e92-81e4eaf4f095
  template:
    metadata:
      labels:
        app: tower
        uuid: 49a02fde-c4c2-4cbb-9e92-81e4eaf4f095
    spec:
      containers:
      - name: tower
        image: fariaass/com-tower:32
        envFrom:
          - secretRef:
              name: credentials
          - secretRef:
              name: email-config
          - configMapRef:
              name: towers-common-config
        env:
          - name: TOWER_ID
            value: 49a02fde-c4c2-4cbb-9e92-81e4eaf4f095
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
