apiVersion: apps/v1
kind: Deployment
metadata:
  name: v-8355c9fd-333f-4582-a10e-2ab24eb7a297
  namespace: ship
  labels:
    app: ship
    uuid: 8355c9fd-333f-4582-a10e-2ab24eb7a297
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ship
      uuid: 8355c9fd-333f-4582-a10e-2ab24eb7a297
  template:
    metadata:
      labels:
        app: ship
        uuid: 8355c9fd-333f-4582-a10e-2ab24eb7a297
    spec:
      containers:
      - name: ship
        image: fariaass/mobility-core:11
        args:
          - "8355c9fd-333f-4582-a10e-2ab24eb7a297"
          - "ship"
          - "70.2"
          - "70.8"
          - "800"
          - "towers-svc.tower.svc.cluster.local"
        envFrom:
          - secretRef:
              name: rabbitmq-credentials
          - configMapRef:
              name: vehicles-common-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
