apiVersion: apps/v1
kind: Deployment
metadata:
  name: v-edabd59c-5d32-4346-9436-af813f0908c8
  namespace: ship
  labels:
    app: ship
    uuid: edabd59c-5d32-4346-9436-af813f0908c8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ship
      uuid: edabd59c-5d32-4346-9436-af813f0908c8
  template:
    metadata:
      labels:
        app: ship
        uuid: edabd59c-5d32-4346-9436-af813f0908c8
    spec:
      containers:
      - name: ship
        image: fariaass/mobility-core:11
        args:
          - "edabd59c-5d32-4346-9436-af813f0908c8"
          - "ship"
          - "70"
          - "70"
          - "800"
          - "towers-svc.tower.svc.cluster.local"
        envFrom:
          - secretRef:
              name: rabbitmq-credentials
          - configMapRef:
              name: vehicles-common-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
