apiVersion: apps/v1
kind: Deployment
metadata:
  name: v-f63dfc2d-a571-4a03-9e51-ce13e37713da
  namespace: ship
  labels:
    app: ship
    uuid: f63dfc2d-a571-4a03-9e51-ce13e37713da
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ship
      uuid: f63dfc2d-a571-4a03-9e51-ce13e37713da
  template:
    metadata:
      labels:
        app: ship
        uuid: f63dfc2d-a571-4a03-9e51-ce13e37713da
    spec:
      containers:
      - name: ship
        image: fariaass/mobility-core:11
        args:
          - "f63dfc2d-a571-4a03-9e51-ce13e37713da"
          - "ship"
          - "70"
          - "72"
          - "800"
          - "towers-svc.tower.svc.cluster.local"
        envFrom:
          - secretRef:
              name: rabbitmq-credentials
          - configMapRef:
              name: vehicles-common-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
