apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-manager
  namespace: audit-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-manager
  template:
    metadata:
      labels:
        app: audit-manager
    spec:
      containers:
      - name: audit-manager
        image: fariaass/audit-manager:1
        envFrom:
          - secretRef:
              name: credentials
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
