apiVersion: apps/v1
kind: Deployment
metadata:
  name: t-cd4f8ced-61cb-4afa-950b-b7ab5f0e36a4
  namespace: tower
  labels:
    app: tower
    uuid: cd4f8ced-61cb-4afa-950b-b7ab5f0e36a4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tower
      uuid: cd4f8ced-61cb-4afa-950b-b7ab5f0e36a4
  template:
    metadata:
      labels:
        app: tower
        uuid: cd4f8ced-61cb-4afa-950b-b7ab5f0e36a4
    spec:
      containers:
      - name: tower
        image: fariaass/com-tower:32
        envFrom:
          - secretRef:
              name: credentials
          - secretRef:
              name: email-config
          - configMapRef:
              name: towers-common-config
        env:
          - name: TOWER_ID
            value: cd4f8ced-61cb-4afa-950b-b7ab5f0e36a4
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
