apiVersion: apps/v1
kind: Deployment
metadata:
  name: t-5c5cb218-c70c-4964-9adc-08a0072ca76e
  namespace: tower
  labels:
    app: tower
    uuid: 5c5cb218-c70c-4964-9adc-08a0072ca76e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tower
      uuid: 5c5cb218-c70c-4964-9adc-08a0072ca76e
  template:
    metadata:
      labels:
        app: tower
        uuid: 5c5cb218-c70c-4964-9adc-08a0072ca76e
    spec:
      containers:
      - name: tower
        image: fariaass/com-tower:32
        envFrom:
          - secretRef:
              name: credentials
          - secretRef:
              name: email-config
          - configMapRef:
              name: towers-common-config
        env:
          - name: TOWER_ID
            value: 5c5cb218-c70c-4964-9adc-08a0072ca76e
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
