apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-c2a3bbba-6480-4875-8872-bed486f836e1
  namespace: central
  labels:
    app: central
    uuid: c2a3bbba-6480-4875-8872-bed486f836e1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central
      uuid: c2a3bbba-6480-4875-8872-bed486f836e1
  template:
    metadata:
      labels:
        app: central
        uuid: c2a3bbba-6480-4875-8872-bed486f836e1
    spec:
      containers:
      - name: central
        image: fariaass/station-core 
        env:
          - name: DOCKS_QTT
            value: "1"
          - name: HELIPADS_QTT
            value: "1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
