apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-fd2f64b5-baa7-4664-810b-a4f9786b005b
  namespace: platform
  labels:
    app: platform
    uuid: fd2f64b5-baa7-4664-810b-a4f9786b005b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform
      uuid: fd2f64b5-baa7-4664-810b-a4f9786b005b
  template:
    metadata:
      labels:
        app: platform
        uuid: fd2f64b5-baa7-4664-810b-a4f9786b005b
    spec:
      containers:
      - name: platform
        image: fariaass/station-core 
        env:
          - name: DOCKS_QTT
            value: "1"
          - name: HELIPADS_QTT
            value: "1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
