apiVersion: apps/v1
kind: Deployment
metadata:
  name: t-445165c2-4186-4acc-b5e4-cf8d588a8a93
  namespace: tower
  labels:
    app: tower
    uuid: 445165c2-4186-4acc-b5e4-cf8d588a8a93
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tower
      uuid: 445165c2-4186-4acc-b5e4-cf8d588a8a93
  template:
    metadata:
      labels:
        app: tower
        uuid: 445165c2-4186-4acc-b5e4-cf8d588a8a93
    spec:
      containers:
      - name: tower
        image: fariaass/com-tower:4
        envFrom:
          - secretRef:
              name: credentials
          - configMapRef:
              name: towers-common-config
        env:
          - name: TOWER_ID
            value: 445165c2-4186-4acc-b5e4-cf8d588a8a93
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
