apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-063e6790-c617-4193-8242-c8b59c3c2b27
  namespace: platform
  labels:
    app: platform
    uuid: 063e6790-c617-4193-8242-c8b59c3c2b27
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform
      uuid: 063e6790-c617-4193-8242-c8b59c3c2b27
  template:
    metadata:
      labels:
        app: platform
        uuid: 063e6790-c617-4193-8242-c8b59c3c2b27
    spec:
      containers:
      - name: platform
        image: fariaass/station-core 
        env:
          - name: DOCKS_QTT
            value: "1"
          - name: HELIPADS_QTT
            value: "1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
