apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-f64060b0-42db-4bfd-a514-eb77f27ef227
  namespace: platform
  labels:
    app: platform
    uuid: f64060b0-42db-4bfd-a514-eb77f27ef227
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform
      uuid: f64060b0-42db-4bfd-a514-eb77f27ef227
  template:
    metadata:
      labels:
        app: platform
        uuid: f64060b0-42db-4bfd-a514-eb77f27ef227
    spec:
      containers:
      - name: platform
        image: fariaass/station-core 
        env:
          - name: DOCKS_QTT
            value: "1"
          - name: HELIPADS_QTT
            value: "1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
