apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-cce5d06b-8cf5-4751-9cdd-df0349ee9e79
  namespace: central
  labels:
    app: central
    uuid: cce5d06b-8cf5-4751-9cdd-df0349ee9e79
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central
      uuid: cce5d06b-8cf5-4751-9cdd-df0349ee9e79
  template:
    metadata:
      labels:
        app: central
        uuid: cce5d06b-8cf5-4751-9cdd-df0349ee9e79
    spec:
      containers:
      - name: central
        image: fariaass/station-core 
        env:
          - name: DOCKS_QTT
            value: "1"
          - name: HELIPADS_QTT
            value: "1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
