apiVersion: apps/v1
kind: Deployment
metadata:
  name: v-13e575e5-6716-458d-8a6b-5ba002a3a28e
  namespace: helicopter
  labels:
    app: helicopter
    uuid: 13e575e5-6716-458d-8a6b-5ba002a3a28e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helicopter
      uuid: 13e575e5-6716-458d-8a6b-5ba002a3a28e
  template:
    metadata:
      labels:
        app: helicopter
        uuid: 13e575e5-6716-458d-8a6b-5ba002a3a28e
    spec:
      containers:
      - name: helicopter
        image: fariaass/mobility-core:11
        args:
          - "13e575e5-6716-458d-8a6b-5ba002a3a28e"
          - "helicopter"
          - "72"
          - "71"
          - "800"
          - "towers-svc.tower.svc.cluster.local"
        envFrom:
          - secretRef:
              name: rabbitmq-credentials
          - configMapRef:
              name: vehicles-common-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
