apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-manager-api
  namespace: resource-manager-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-manager-api
  template:
    metadata:
      labels:
        app: resource-manager-api
    spec:
      containers:
      - name: resource-manager-api
        image: fariaass/resource-manager-api:6
        ports:
          - containerPort: 4000
        envFrom:
          - secretRef:
              name: db-credentials
          - secretRef:
              name: gitops-credentials
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
