apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resource-manager-api
  namespace: resource-manager-api
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod" 
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://maritime-flow.souzavinicius.com"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - maritime-flow-api.souzavinicius.com
      secretName: maritime-flow-api-tls-secret
  rules:
    - host: maritime-flow-api.souzavinicius.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: resource-manager-api
                port:
                  number: 4000
