apiVersion: apps/v1
kind: Deployment
metadata:
  name: t-369cd047-284a-4bb8-8804-68f4c83f1942
  namespace: tower
  labels:
    app: tower
    uuid: 369cd047-284a-4bb8-8804-68f4c83f1942
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tower
      uuid: 369cd047-284a-4bb8-8804-68f4c83f1942
  template:
    metadata:
      labels:
        app: tower
        uuid: 369cd047-284a-4bb8-8804-68f4c83f1942
    spec:
      containers:
      - name: tower
        image: fariaass/com-tower:37
        envFrom:
          - secretRef:
              name: credentials
          - secretRef:
              name: email-config
          - configMapRef:
              name: towers-common-config
        env:
          - name: TOWER_ID
            value: 369cd047-284a-4bb8-8804-68f4c83f1942
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
