apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-872b12d7-f9ef-4b2e-84d6-09be2634d7ee
  namespace: central
  labels:
    app: central
    uuid: 872b12d7-f9ef-4b2e-84d6-09be2634d7ee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central
      uuid: 872b12d7-f9ef-4b2e-84d6-09be2634d7ee
  template:
    metadata:
      labels:
        app: central
        uuid: 872b12d7-f9ef-4b2e-84d6-09be2634d7ee
    spec:
      containers:
      - name: central
        image: fariaass/station-core 
        env:
          - name: DOCKS_QTT
            value: "1"
          - name: HELIPADS_QTT
            value: "1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
